export const SEED_VERBS = [
  { infinitive: "zijn", past: "was", participle: "geweest", meaning: "to be" },
  { infinitive: "hebben", past: "had", participle: "gehad", meaning: "to have" },
  { infinitive: "gaan", past: "ging", participle: "gegaan", meaning: "to go" },
  { infinitive: "komen", past: "kwam", participle: "gekomen", meaning: "to come" },
  { infinitive: "doen", past: "deed", participle: "gedaan", meaning: "to do" },
  { infinitive: "zien", past: "zag", participle: "gezien", meaning: "to see" },
  { infinitive: "weten", past: "wist", participle: "geweten", meaning: "to know" },
  { infinitive: "krijgen", past: "kreeg", participle: "gekregen", meaning: "to get / receive" },
  { infinitive: "geven", past: "gaf", participle: "gegeven", meaning: "to give" },
  { infinitive: "nemen", past: "nam", participle: "genomen", meaning: "to take" },
  { infinitive: "blijven", past: "bleef", participle: "gebleven", meaning: "to stay" },
  { infinitive: "lopen", past: "liep", participle: "gelopen", meaning: "to walk / run" },
  { infinitive: "staan", past: "stond", participle: "gestaan", meaning: "to stand" },
  { infinitive: "zitten", past: "zat", participle: "gezeten", meaning: "to sit" },
  { infinitive: "liggen", past: "lag", participle: "gelegen", meaning: "to lie" },
  { infinitive: "spreken", past: "sprak", participle: "gesproken", meaning: "to speak" },
  { infinitive: "lezen", past: "las", participle: "gelezen", meaning: "to read" },
  { infinitive: "schrijven", past: "schreef", participle: "geschreven", meaning: "to write" },
  { infinitive: "drinken", past: "dronk", participle: "gedronken", meaning: "to drink" },
  { infinitive: "eten", past: "at", participle: "gegeten", meaning: "to eat" },
  { infinitive: "slapen", past: "sliep", participle: "geslapen", meaning: "to sleep" },
  { infinitive: "vinden", past: "vond", participle: "gevonden", meaning: "to find" },
  { infinitive: "helpen", past: "hielp", participle: "geholpen", meaning: "to help" },
  { infinitive: "zwemmen", past: "zwom", participle: "gezwommen", meaning: "to swim" },
  { infinitive: "vliegen", past: "vloog", participle: "gevlogen", meaning: "to fly" },
  { infinitive: "winnen", past: "won", participle: "gewonnen", meaning: "to win" },
  { infinitive: "begrijpen", past: "begreep", participle: "begrepen", meaning: "to understand" },
  { infinitive: "rijden", past: "reed", participle: "gereden", meaning: "to drive" },
  { infinitive: "vergeten", past: "vergat", participle: "vergeten", meaning: "to forget" },
  { infinitive: "beginnen", past: "begon", participle: "begonnen", meaning: "to begin" },
  { infinitive: "verliezen", past: "verloor", participle: "verloren", meaning: "to lose" },
  { infinitive: "sluiten", past: "sloot", participle: "gesloten", meaning: "to close" },
  { infinitive: "breken", past: "brak", participle: "gebroken", meaning: "to break" },
  { infinitive: "trekken", past: "trok", participle: "getrokken", meaning: "to pull" },
  { infinitive: "roepen", past: "riep", participle: "geroepen", meaning: "to call" },
  { infinitive: "bieden", past: "bood", participle: "geboden", meaning: "to offer" },
  { infinitive: "dragen", past: "droeg", participle: "gedragen", meaning: "to carry / wear" },
  { infinitive: "zingen", past: "zong", participle: "gezongen", meaning: "to sing" },
  { infinitive: "springen", past: "sprong", participle: "gesprongen", meaning: "to jump" },
  { infinitive: "vechten", past: "vocht", participle: "gevochten", meaning: "to fight" },
  { infinitive: "werpen", past: "wierp", participle: "geworpen", meaning: "to throw" },
  { infinitive: "sterven", past: "stierf", participle: "gestorven", meaning: "to die" },
  { infinitive: "kiezen", past: "koos", participle: "gekozen", meaning: "to choose" },
  { infinitive: "bewegen", past: "bewoog", participle: "bewogen", meaning: "to move" },
  { infinitive: "verlaten", past: "verliet", participle: "verlaten", meaning: "to leave / abandon" },
  { infinitive: "vergelijken", past: "vergeleek", participle: "vergeleken", meaning: "to compare" },
  { infinitive: "genieten", past: "genoot", participle: "genoten", meaning: "to enjoy" },
  { infinitive: "verdwijnen", past: "verdween", participle: "verdwenen", meaning: "to disappear" },
  { infinitive: "snijden", past: "sneed", participle: "gesneden", meaning: "to cut" },
  { infinitive: "binden", past: "bond", participle: "gebonden", meaning: "to bind / tie" },
  { infinitive: "kruipen", past: "kroop", participle: "gekropen", meaning: "to crawl" },
  { infinitive: "zwijgen", past: "zweeg", participle: "gezwegen", meaning: "to be silent" },
  { infinitive: "wegen", past: "woog", participle: "gewogen", meaning: "to weigh" },
  { infinitive: "wijzen", past: "wees", participle: "gewezen", meaning: "to point" },
  { infinitive: "graven", past: "groef", participle: "gegraven", meaning: "to dig" },
  { infinitive: "hangen", past: "hing", participle: "gehangen", meaning: "to hang" },
  { infinitive: "blazen", past: "blies", participle: "geblazen", meaning: "to blow" },
  { infinitive: "stelen", past: "stal", participle: "gestolen", meaning: "to steal" },
  { infinitive: "vriezen", past: "vroor", participle: "gevroren", meaning: "to freeze" },
  { infinitive: "lijken", past: "leek", participle: "geleken", meaning: "to seem" },
  { infinitive: "ontvangen", past: "ontving", participle: "ontvangen", meaning: "to receive" },
  { infinitive: "besluiten", past: "besloot", participle: "besloten", meaning: "to decide" },
  { infinitive: "verbieden", past: "verbood", participle: "verboden", meaning: "to forbid" },
  { infinitive: "houden", past: "hield", participle: "gehouden", meaning: "to hold / love" },
  { infinitive: "zinken", past: "zonk", participle: "gezonken", meaning: "to sink" },
  { infinitive: "drijven", past: "dreef", participle: "gedreven", meaning: "to float" },
  { infinitive: "heffen", past: "hief", participle: "geheven", meaning: "to lift" },
  { infinitive: "schenken", past: "schonk", participle: "geschonken", meaning: "to give / pour" },
  { infinitive: "krimpen", past: "kromp", participle: "gekrompen", meaning: "to shrink" },
  { infinitive: "zwerven", past: "zwierf", participle: "gezworven", meaning: "to wander" },
  { infinitive: "ontstaan", past: "ontstond", participle: "ontstaan", meaning: "to arise" },
  { infinitive: "raden", past: "ried", participle: "geraden", meaning: "to guess" },
  { infinitive: "slaan", past: "sloeg", participle: "geslagen", meaning: "to hit" },
  { infinitive: "gieten", past: "goot", participle: "gegoten", meaning: "to pour" },
  { infinitive: "schieten", past: "schoot", participle: "geschoten", meaning: "to shoot" },
  { infinitive: "ervaren", past: "ervoer", participle: "ervaren", meaning: "to experience" },
  { infinitive: "vergeven", past: "vergaf", participle: "vergeven", meaning: "to forgive" },
  { infinitive: "blijken", past: "bleek", participle: "gebleken", meaning: "to turn out" },
  { infinitive: "fluiten", past: "floot", participle: "gefloten", meaning: "to whistle" },
  { infinitive: "duiken", past: "dook", participle: "gedoken", meaning: "to dive" },
  { infinitive: "ruiken", past: "rook", participle: "geroken", meaning: "to smell" },
  { infinitive: "zuigen", past: "zoog", participle: "gezogen", meaning: "to suck" },
  { infinitive: "schuiven", past: "schoof", participle: "geschoven", meaning: "to push / slide" },
  { infinitive: "buigen", past: "boog", participle: "gebogen", meaning: "to bend" },
  { infinitive: "schijnen", past: "scheen", participle: "geschenen", meaning: "to shine" },
  { infinitive: "lijden", past: "leed", participle: "geleden", meaning: "to suffer" },
  { infinitive: "mijden", past: "meed", participle: "gemeden", meaning: "to avoid" },
  { infinitive: "genezen", past: "genas", participle: "genezen", meaning: "to recover / heal" },
  { infinitive: "vallen", past: "viel", participle: "gevallen", meaning: "to fall" },
  { infinitive: "bevelen", past: "beval", participle: "bevolen", meaning: "to command" },
  { infinitive: "zenden", past: "zond", participle: "gezonden", meaning: "to send" },
  { infinitive: "bevinden", past: "bevond", participle: "bevonden", meaning: "to be located" },
  { infinitive: "schrikken", past: "schrok", participle: "geschrokken", meaning: "to get scared" },
  { infinitive: "scheppen", past: "schiep", participle: "geschapen", meaning: "to create" },
  { infinitive: "rijzen", past: "rees", participle: "gerezen", meaning: "to rise" },
  { infinitive: "werven", past: "wierf", participle: "geworven", meaning: "to recruit" },
  { infinitive: "bewijzen", past: "bewees", participle: "bewezen", meaning: "to prove" },
  { infinitive: "spinnen", past: "spon", participle: "gesponnen", meaning: "to spin" },
  { infinitive: "wijken", past: "week", participle: "geweken", meaning: "to retreat" },
  { infinitive: "ontbreken", past: "ontbrak", participle: "ontbroken", meaning: "to be missing" },
  { infinitive: "bevallen", past: "beviel", participle: "bevallen", meaning: "to please / give birth" },
  { infinitive: "betreffen", past: "betrof", participle: "betroffen", meaning: "to concern" },
  { infinitive: "bekijken", past: "bekeek", participle: "bekeken", meaning: "to examine" },
  { infinitive: "begraven", past: "begroef", participle: "begraven", meaning: "to bury" },
  { infinitive: "zwellen", past: "zwol", participle: "gezwollen", meaning: "to swell" },
  { infinitive: "beschrijven", past: "beschreef", participle: "beschreven", meaning: "to describe" },
  { infinitive: "bestaan", past: "bestond", participle: "bestaan", meaning: "to exist" },
  { infinitive: "begeven", past: "begaf", participle: "begeven", meaning: "to set out" },
  { infinitive: "behouden", past: "behield", participle: "behouden", meaning: "to retain" },
  { infinitive: "ontslaan", past: "ontsloeg", participle: "ontslagen", meaning: "to dismiss" },
  { infinitive: "onthouden", past: "onthield", participle: "onthouden", meaning: "to remember" },
  { infinitive: "ontwerpen", past: "ontwierp", participle: "ontworpen", meaning: "to design" },
  { infinitive: "bezitten", past: "bezat", participle: "bezeten", meaning: "to possess" },
  { infinitive: "verzinnen", past: "verzon", participle: "verzonnen", meaning: "to invent" },
  { infinitive: "verwerven", past: "verwierf", participle: "verworven", meaning: "to acquire" },
  { infinitive: "verbinden", past: "verbond", participle: "verbonden", meaning: "to connect" },
  { infinitive: "verstaan", past: "verstond", participle: "verstaan", meaning: "to understand (hearing)" },
  { infinitive: "voorzien", past: "voorzag", participle: "voorzien", meaning: "to provide / foresee" },
  { infinitive: "vergaan", past: "verging", participle: "vergaan", meaning: "to perish" },
  { infinitive: "ontnemen", past: "ontnam", participle: "ontnomen", meaning: "to take away" },
];

export const SEED_NOUNS = [
  { word: "huis", article: "het", meaning: "house" },
  { word: "kind", article: "het", meaning: "child" },
  { word: "meisje", article: "het", meaning: "girl" },
  { word: "boek", article: "het", meaning: "book" },
  { word: "water", article: "het", meaning: "water" },
  { word: "brood", article: "het", meaning: "bread" },
  { word: "bier", article: "het", meaning: "beer" },
  { word: "eten", article: "het", meaning: "food" },
  { word: "jaar", article: "het", meaning: "year" },
  { word: "station", article: "het", meaning: "station" },
  { word: "land", article: "het", meaning: "country" },
  { word: "geld", article: "het", meaning: "money" },
  { word: "weer", article: "het", meaning: "weather" },
  { word: "kantoor", article: "het", meaning: "office" },
  { word: "raam", article: "het", meaning: "window" },
  { word: "paard", article: "het", meaning: "horse" },
  { word: "glas", article: "het", meaning: "glass" },
  { word: "bed", article: "het", meaning: "bed" },
  { word: "uur", article: "het", meaning: "hour" },
  { word: "feest", article: "het", meaning: "party" },
  { word: "man", article: "de", meaning: "man" },
  { word: "vrouw", article: "de", meaning: "woman" },
  { word: "jongen", article: "de", meaning: "boy" },
  { word: "moeder", article: "de", meaning: "mother" },
  { word: "vader", article: "de", meaning: "father" },
  { word: "familie", article: "de", meaning: "family" },
  { word: "vriend", article: "de", meaning: "friend" },
  { word: "tijd", article: "de", meaning: "time" },
  { word: "week", article: "de", meaning: "week" },
  { word: "dag", article: "de", meaning: "day" },
  { word: "maand", article: "de", meaning: "month" },
  { word: "avond", article: "de", meaning: "evening" },
  { word: "straat", article: "de", meaning: "street" },
  { word: "auto", article: "de", meaning: "car" },
  { word: "fiets", article: "de", meaning: "bicycle" },
  { word: "stad", article: "de", meaning: "city" },
  { word: "taal", article: "de", meaning: "language" },
  { word: "koffie", article: "de", meaning: "coffee" },
  { word: "hond", article: "de", meaning: "dog" },
  { word: "job", article: "de", meaning: "job" },
  { word: "probleem", article: "het", meaning: "problem" },
  { word: "idee", article: "het", meaning: "idea" },
  { word: "antwoord", article: "het", meaning: "answer" },
  { word: "verhaal", article: "het", meaning: "story" },
  { word: "bos", article: "het", meaning: "forest" },
  { word: "strand", article: "het", meaning: "beach" },
  { word: "meer", article: "het", meaning: "lake" },
  { word: "eiland", article: "het", meaning: "island" },
  { word: "hart", article: "het", meaning: "heart" },
  { word: "hoofd", article: "het", meaning: "head" },
  { word: "oog", article: "het", meaning: "eye" },
  { word: "oor", article: "het", meaning: "ear" },
  { word: "haar", article: "het", meaning: "hair" },
  { word: "lichaam", article: "het", meaning: "body" },
  { word: "gezicht", article: "het", meaning: "face" },
  { word: "gevoel", article: "het", meaning: "feeling" },
  { word: "leven", article: "het", meaning: "life" },
  { word: "ziekenhuis", article: "het", meaning: "hospital" },
  { word: "museum", article: "het", meaning: "museum" },
  { word: "restaurant", article: "het", meaning: "restaurant" },
  { word: "hotel", article: "het", meaning: "hotel" },
  { word: "zwembad", article: "het", meaning: "swimming pool" },
  { word: "vliegtuig", article: "het", meaning: "airplane" },
  { word: "ticket", article: "het", meaning: "ticket" },
  { word: "cadeau", article: "het", meaning: "gift" },
  { word: "ontbijt", article: "het", meaning: "breakfast" },
  { word: "toilet", article: "het", meaning: "toilet" },
  { word: "dak", article: "het", meaning: "roof" },
  { word: "ei", article: "het", meaning: "egg" },
  { word: "stuk", article: "het", meaning: "piece" },
  { word: "naam", article: "de", meaning: "name" },
  { word: "school", article: "de", meaning: "school" },
  { word: "winkel", article: "de", meaning: "shop" },
  { word: "markt", article: "de", meaning: "market" },
  { word: "kerk", article: "de", meaning: "church" },
  { word: "brug", article: "de", meaning: "bridge" },
  { word: "zee", article: "de", meaning: "sea" },
  { word: "rivier", article: "de", meaning: "river" },
  { word: "berg", article: "de", meaning: "mountain" },
  { word: "tafel", article: "de", meaning: "table" },
  { word: "stoel", article: "de", meaning: "chair" },
  { word: "deur", article: "de", meaning: "door" },
  { word: "tuin", article: "de", meaning: "garden" },
  { word: "keuken", article: "de", meaning: "kitchen" },
  { word: "winter", article: "de", meaning: "winter" },
  { word: "zomer", article: "de", meaning: "summer" },
  { word: "lente", article: "de", meaning: "spring" },
  { word: "herfst", article: "de", meaning: "autumn" },
  { word: "regen", article: "de", meaning: "rain" },
  { word: "zon", article: "de", meaning: "sun" },
  { word: "bloem", article: "de", meaning: "flower" },
  { word: "boom", article: "de", meaning: "tree" },
  { word: "muur", article: "de", meaning: "wall" },
  { word: "vis", article: "de", meaning: "fish" },
  { word: "vogel", article: "de", meaning: "bird" },
  { word: "soep", article: "de", meaning: "soup" },
  { word: "wijn", article: "de", meaning: "wine" },
  { word: "melk", article: "de", meaning: "milk" },
  { word: "thee", article: "de", meaning: "tea" },
  { word: "collega", article: "de", meaning: "colleague" },
  { word: "centrum", article: "het", meaning: "center" },
  { word: "prijs", article: "de", meaning: "price" },
  { word: "paspoort", article: "het", meaning: "passport" },
  { word: "plek", article: "de", meaning: "spot / place" },
  { word: "verschil", article: "het", meaning: "difference" },
  { word: "wereld", article: "de", meaning: "world" },
  { word: "bedrijf", article: "het", meaning: "company" },
  { word: "mens", article: "de", meaning: "person / human" },
  { word: "project", article: "het", meaning: "project" },
  { word: "persoon", article: "de", meaning: "person" },
  { word: "bericht", article: "het", meaning: "message" },
  { word: "buurman", article: "de", meaning: "male neighbor" },
  { word: "cijfer", article: "het", meaning: "grade / digit" },
  { word: "buurvrouw", article: "de", meaning: "female neighbor" },
  { word: "getal", article: "het", meaning: "number" },
  { word: "baby", article: "de", meaning: "baby" },
  { word: "examen", article: "het", meaning: "exam" },
  { word: "tiener", article: "de", meaning: "teenager" },
  { word: "diploma", article: "het", meaning: "diploma" },
  { word: "student", article: "de", meaning: "student" },
  { word: "contract", article: "het", meaning: "contract" },
  { word: "leraar", article: "de", meaning: "teacher" },
  { word: "apparaat", article: "het", meaning: "device" },
  { word: "dokter", article: "de", meaning: "doctor" },
  { word: "scherm", article: "het", meaning: "screen" },
  { word: "tandarts", article: "de", meaning: "dentist" },
  { word: "toetsenbord", article: "het", meaning: "keyboard" },
  { word: "verpleegster", article: "de", meaning: "nurse" },
  { word: "wachtwoord", article: "het", meaning: "password" },
  { word: "baas", article: "de", meaning: "boss" },
  { word: "netwerk", article: "het", meaning: "network" },
  { word: "werkgever", article: "de", meaning: "employer" },
  { word: "programma", article: "het", meaning: "program" },
  { word: "werknemer", article: "de", meaning: "employee" },
  { word: "document", article: "het", meaning: "document" },
  { word: "klant", article: "de", meaning: "customer" },
  { word: "formulier", article: "het", meaning: "form" },
  { word: "gast", article: "de", meaning: "guest" },
  { word: "pakket", article: "het", meaning: "parcel" },
  { word: "buurt", article: "de", meaning: "neighborhood" },
  { word: "adres", article: "het", meaning: "address" },
  { word: "wijk", article: "de", meaning: "district" },
  { word: "verzoek", article: "het", meaning: "request" },
  { word: "provincie", article: "de", meaning: "province" },
  { word: "advies", article: "het", meaning: "advice" },
  { word: "hoofdstad", article: "de", meaning: "capital" },
  { word: "besluit", article: "het", meaning: "decision" },
  { word: "luchthaven", article: "de", meaning: "airport" },
  { word: "voorbeeld", article: "het", meaning: "example" },
  { word: "haven", article: "de", meaning: "harbor" },
  { word: "doel", article: "het", meaning: "goal" },
  { word: "bus", article: "de", meaning: "bus" },
  { word: "plan", article: "het", meaning: "plan" },
  { word: "tram", article: "de", meaning: "tram" },
  { word: "einde", article: "het", meaning: "end" },
  { word: "metro", article: "de", meaning: "metro" },
  { word: "begin", article: "het", meaning: "beginning" },
  { word: "boot", article: "de", meaning: "boat" },
  { word: "midden", article: "het", meaning: "middle" },
  { word: "taxi", article: "de", meaning: "taxi" },
  { word: "ijs", article: "het", meaning: "ice cream / ice" },
  { word: "straatlamp", article: "de", meaning: "streetlamp" },
  { word: "sap", article: "het", meaning: "juice" },
  { word: "prullenbak", article: "de", meaning: "trash can" },
  { word: "vlees", article: "het", meaning: "meat" },
  { word: "bakker", article: "de", meaning: "baker" },
  { word: "fruit", article: "het", meaning: "fruit" },
  { word: "slager", article: "de", meaning: "butcher" },
  { word: "avondeten", article: "het", meaning: "dinner" },
  { word: "apotheek", article: "de", meaning: "pharmacy" },
  { word: "bord", article: "het", meaning: "plate" },
  { word: "bibliotheek", article: "de", meaning: "library" },
  { word: "mes", article: "het", meaning: "knife" },
  { word: "bioscoop", article: "de", meaning: "cinema" },
  { word: "kopje", article: "het", meaning: "cup" },
  { word: "bar", article: "de", meaning: "bar" },
  { word: "servet", article: "het", meaning: "napkin" },
  { word: "discotheek", article: "de", meaning: "nightclub" },
  { word: "tafelkleed", article: "het", meaning: "tablecloth" },
  { word: "afspraak", article: "de", meaning: "appointment" },
  { word: "licht", article: "het", meaning: "light" },
  { word: "vergadering", article: "de", meaning: "meeting" },
  { word: "vuur", article: "het", meaning: "fire" },
  { word: "pauze", article: "de", meaning: "break" },
  { word: "schip", article: "het", meaning: "ship" },
  { word: "vakantie", article: "de", meaning: "vacation" },
  { word: "meubilair", article: "het", meaning: "furniture" },
  { word: "reis", article: "de", meaning: "trip" },
  { word: "tapijt", article: "het", meaning: "carpet" },
  { word: "bagage", article: "de", meaning: "luggage" },
  { word: "kussen", article: "het", meaning: "pillow" },
  { word: "koffer", article: "de", meaning: "suitcase" },
  { word: "laken", article: "het", meaning: "sheet" },
  { word: "tas", article: "de", meaning: "bag" },
  { word: "bezoek", article: "het", meaning: "visit" },
  { word: "portemonnee", article: "de", meaning: "wallet" },
  { word: "gesprek", article: "het", meaning: "conversation" },
  { word: "sleutel", article: "de", meaning: "key" },
  { word: "succes", article: "het", meaning: "success" },
  { word: "bril", article: "de", meaning: "glasses" },
];

import { Verb } from "./models/Verb.js";
import { Noun } from "./models/Noun.js";
import { Stats } from "./models/Stats.js";

export async function seedIfNeeded() {
  const now = new Date();
  const verbRows = SEED_VERBS.map((v) => ({ ...v, next_review: now }));
  const nounRows = SEED_NOUNS.map((n) => ({ ...n, next_review: now }));

  const [verbsBefore, nounsBefore] = await Promise.all([Verb.count(), Noun.count()]);

  // updateOnDuplicate refreshes the meaning column on existing rows (e.g. when we
  // change a translation) without touching level/next_review/attempts/mistakes —
  // so user progress survives content edits across deploys.
  await Verb.bulkCreate(verbRows, { updateOnDuplicate: ["meaning"] });
  await Noun.bulkCreate(nounRows, { updateOnDuplicate: ["meaning"] });
  await Stats.findOrCreate({ where: { id: 1 }, defaults: { id: 1 } });

  const [verbsAfter, nounsAfter] = await Promise.all([Verb.count(), Noun.count()]);
  return {
    verbsAdded: verbsAfter - verbsBefore,
    nounsAdded: nounsAfter - nounsBefore,
    verbsTotal: verbsAfter,
    nounsTotal: nounsAfter,
  };
}
