export const SEED_VERBS = [
  { infinitive: "zijn", past: "was", participle: "geweest", meaning_ru: "быть" },
  { infinitive: "hebben", past: "had", participle: "gehad", meaning_ru: "иметь" },
  { infinitive: "gaan", past: "ging", participle: "gegaan", meaning_ru: "идти" },
  { infinitive: "komen", past: "kwam", participle: "gekomen", meaning_ru: "приходить" },
  { infinitive: "doen", past: "deed", participle: "gedaan", meaning_ru: "делать" },
  { infinitive: "zien", past: "zag", participle: "gezien", meaning_ru: "видеть" },
  { infinitive: "weten", past: "wist", participle: "geweten", meaning_ru: "знать" },
  { infinitive: "krijgen", past: "kreeg", participle: "gekregen", meaning_ru: "получать" },
  { infinitive: "geven", past: "gaf", participle: "gegeven", meaning_ru: "давать" },
  { infinitive: "nemen", past: "nam", participle: "genomen", meaning_ru: "брать" },
  { infinitive: "blijven", past: "bleef", participle: "gebleven", meaning_ru: "оставаться" },
  { infinitive: "lopen", past: "liep", participle: "gelopen", meaning_ru: "идти / бежать" },
  { infinitive: "staan", past: "stond", participle: "gestaan", meaning_ru: "стоять" },
  { infinitive: "zitten", past: "zat", participle: "gezeten", meaning_ru: "сидеть" },
  { infinitive: "liggen", past: "lag", participle: "gelegen", meaning_ru: "лежать" },
  { infinitive: "spreken", past: "sprak", participle: "gesproken", meaning_ru: "говорить" },
  { infinitive: "lezen", past: "las", participle: "gelezen", meaning_ru: "читать" },
  { infinitive: "schrijven", past: "schreef", participle: "geschreven", meaning_ru: "писать" },
  { infinitive: "drinken", past: "dronk", participle: "gedronken", meaning_ru: "пить" },
  { infinitive: "eten", past: "at", participle: "gegeten", meaning_ru: "есть (кушать)" },
  { infinitive: "slapen", past: "sliep", participle: "geslapen", meaning_ru: "спать" },
  { infinitive: "vinden", past: "vond", participle: "gevonden", meaning_ru: "находить" },
  { infinitive: "helpen", past: "hielp", participle: "geholpen", meaning_ru: "помогать" },
  { infinitive: "zwemmen", past: "zwom", participle: "gezwommen", meaning_ru: "плавать" },
  { infinitive: "vliegen", past: "vloog", participle: "gevlogen", meaning_ru: "летать" },
  { infinitive: "winnen", past: "won", participle: "gewonnen", meaning_ru: "выигрывать" },
  { infinitive: "begrijpen", past: "begreep", participle: "begrepen", meaning_ru: "понимать" },
  { infinitive: "rijden", past: "reed", participle: "gereden", meaning_ru: "ехать" },
  { infinitive: "vergeten", past: "vergat", participle: "vergeten", meaning_ru: "забывать" },
  { infinitive: "beginnen", past: "begon", participle: "begonnen", meaning_ru: "начинать" },
  { infinitive: "verliezen", past: "verloor", participle: "verloren", meaning_ru: "терять" },
  { infinitive: "sluiten", past: "sloot", participle: "gesloten", meaning_ru: "закрывать" },
  { infinitive: "breken", past: "brak", participle: "gebroken", meaning_ru: "ломать" },
  { infinitive: "trekken", past: "trok", participle: "getrokken", meaning_ru: "тянуть" },
  { infinitive: "roepen", past: "riep", participle: "geroepen", meaning_ru: "звать" },
  { infinitive: "bieden", past: "bood", participle: "geboden", meaning_ru: "предлагать" },
  { infinitive: "dragen", past: "droeg", participle: "gedragen", meaning_ru: "носить" },
  { infinitive: "zingen", past: "zong", participle: "gezongen", meaning_ru: "петь" },
  { infinitive: "springen", past: "sprong", participle: "gesprongen", meaning_ru: "прыгать" },
  { infinitive: "vechten", past: "vocht", participle: "gevochten", meaning_ru: "драться" },
  { infinitive: "werpen", past: "wierp", participle: "geworpen", meaning_ru: "бросать" },
  { infinitive: "sterven", past: "stierf", participle: "gestorven", meaning_ru: "умирать" },
  { infinitive: "kiezen", past: "koos", participle: "gekozen", meaning_ru: "выбирать" },
  { infinitive: "bewegen", past: "bewoog", participle: "bewogen", meaning_ru: "двигать(ся)" },
  { infinitive: "verlaten", past: "verliet", participle: "verlaten", meaning_ru: "покидать" },
  { infinitive: "vergelijken", past: "vergeleek", participle: "vergeleken", meaning_ru: "сравнивать" },
  { infinitive: "genieten", past: "genoot", participle: "genoten", meaning_ru: "наслаждаться" },
  { infinitive: "verdwijnen", past: "verdween", participle: "verdwenen", meaning_ru: "исчезать" },
  { infinitive: "snijden", past: "sneed", participle: "gesneden", meaning_ru: "резать" },
  { infinitive: "binden", past: "bond", participle: "gebonden", meaning_ru: "связывать" },
  { infinitive: "kruipen", past: "kroop", participle: "gekropen", meaning_ru: "ползти" },
  { infinitive: "zwijgen", past: "zweeg", participle: "gezwegen", meaning_ru: "молчать" },
  { infinitive: "wegen", past: "woog", participle: "gewogen", meaning_ru: "взвешивать" },
  { infinitive: "wijzen", past: "wees", participle: "gewezen", meaning_ru: "указывать" },
  { infinitive: "graven", past: "groef", participle: "gegraven", meaning_ru: "копать" },
  { infinitive: "hangen", past: "hing", participle: "gehangen", meaning_ru: "висеть" },
  { infinitive: "blazen", past: "blies", participle: "geblazen", meaning_ru: "дуть" },
  { infinitive: "stelen", past: "stal", participle: "gestolen", meaning_ru: "красть" },
  { infinitive: "vriezen", past: "vroor", participle: "gevroren", meaning_ru: "морозить" },
  { infinitive: "lijken", past: "leek", participle: "geleken", meaning_ru: "казаться" },
  { infinitive: "ontvangen", past: "ontving", participle: "ontvangen", meaning_ru: "принимать" },
  { infinitive: "besluiten", past: "besloot", participle: "besloten", meaning_ru: "решать" },
  { infinitive: "verbieden", past: "verbood", participle: "verboden", meaning_ru: "запрещать" },
  { infinitive: "houden", past: "hield", participle: "gehouden", meaning_ru: "держать / любить" },
  { infinitive: "zinken", past: "zonk", participle: "gezonken", meaning_ru: "тонуть" },
  { infinitive: "drijven", past: "dreef", participle: "gedreven", meaning_ru: "плыть" },
  { infinitive: "heffen", past: "hief", participle: "geheven", meaning_ru: "поднимать" },
  { infinitive: "schenken", past: "schonk", participle: "geschonken", meaning_ru: "дарить" },
  { infinitive: "krimpen", past: "kromp", participle: "gekrompen", meaning_ru: "сжиматься" },
  { infinitive: "zwerven", past: "zwierf", participle: "gezworven", meaning_ru: "бродить" },
  { infinitive: "ontstaan", past: "ontstond", participle: "ontstaan", meaning_ru: "возникать" },
  { infinitive: "raden", past: "ried", participle: "geraden", meaning_ru: "угадывать" },
  { infinitive: "slaan", past: "sloeg", participle: "geslagen", meaning_ru: "бить" },
  { infinitive: "gieten", past: "goot", participle: "gegoten", meaning_ru: "лить" },
  { infinitive: "schieten", past: "schoot", participle: "geschoten", meaning_ru: "стрелять" },
  { infinitive: "ervaren", past: "ervoer", participle: "ervaren", meaning_ru: "испытывать" },
  { infinitive: "vergeven", past: "vergaf", participle: "vergeven", meaning_ru: "прощать" },
  { infinitive: "blijken", past: "bleek", participle: "gebleken", meaning_ru: "оказываться" },
  { infinitive: "fluiten", past: "floot", participle: "gefloten", meaning_ru: "свистеть" },
  { infinitive: "duiken", past: "dook", participle: "gedoken", meaning_ru: "нырять" },
  { infinitive: "ruiken", past: "rook", participle: "geroken", meaning_ru: "пахнуть" },
  { infinitive: "zuigen", past: "zoog", participle: "gezogen", meaning_ru: "сосать" },
  { infinitive: "schuiven", past: "schoof", participle: "geschoven", meaning_ru: "двигать" },
  { infinitive: "buigen", past: "boog", participle: "gebogen", meaning_ru: "гнуть" },
  { infinitive: "schijnen", past: "scheen", participle: "geschenen", meaning_ru: "светить" },
  { infinitive: "lijden", past: "leed", participle: "geleden", meaning_ru: "страдать" },
  { infinitive: "mijden", past: "meed", participle: "gemeden", meaning_ru: "избегать" },
  { infinitive: "genezen", past: "genas", participle: "genezen", meaning_ru: "выздоравливать" },
  { infinitive: "vallen", past: "viel", participle: "gevallen", meaning_ru: "падать" },
  { infinitive: "bevelen", past: "beval", participle: "bevolen", meaning_ru: "приказывать" },
  { infinitive: "zenden", past: "zond", participle: "gezonden", meaning_ru: "посылать" },
  { infinitive: "bevinden", past: "bevond", participle: "bevonden", meaning_ru: "находиться" },
  { infinitive: "schrikken", past: "schrok", participle: "geschrokken", meaning_ru: "пугаться" },
  { infinitive: "scheppen", past: "schiep", participle: "geschapen", meaning_ru: "творить" },
  { infinitive: "rijzen", past: "rees", participle: "gerezen", meaning_ru: "подниматься" },
  { infinitive: "werven", past: "wierf", participle: "geworven", meaning_ru: "вербовать" },
  { infinitive: "bewijzen", past: "bewees", participle: "bewezen", meaning_ru: "доказывать" },
  { infinitive: "spinnen", past: "spon", participle: "gesponnen", meaning_ru: "прясти" },
  { infinitive: "wijken", past: "week", participle: "geweken", meaning_ru: "отступать" },
  { infinitive: "ontbreken", past: "ontbrak", participle: "ontbroken", meaning_ru: "отсутствовать" },
  { infinitive: "bevallen", past: "beviel", participle: "bevallen", meaning_ru: "нравиться" },
  { infinitive: "betreffen", past: "betrof", participle: "betroffen", meaning_ru: "касаться" },
  { infinitive: "bekijken", past: "bekeek", participle: "bekeken", meaning_ru: "рассматривать" },
  { infinitive: "begraven", past: "begroef", participle: "begraven", meaning_ru: "хоронить" },
  { infinitive: "zwellen", past: "zwol", participle: "gezwollen", meaning_ru: "раздуваться" },
  { infinitive: "beschrijven", past: "beschreef", participle: "beschreven", meaning_ru: "описывать" },
  { infinitive: "bestaan", past: "bestond", participle: "bestaan", meaning_ru: "существовать" },
  { infinitive: "begeven", past: "begaf", participle: "begeven", meaning_ru: "отправляться" },
  { infinitive: "behouden", past: "behield", participle: "behouden", meaning_ru: "сохранять" },
  { infinitive: "ontslaan", past: "ontsloeg", participle: "ontslagen", meaning_ru: "увольнять" },
  { infinitive: "onthouden", past: "onthield", participle: "onthouden", meaning_ru: "запоминать" },
  { infinitive: "ontwerpen", past: "ontwierp", participle: "ontworpen", meaning_ru: "проектировать" },
  { infinitive: "bezitten", past: "bezat", participle: "bezeten", meaning_ru: "обладать" },
  { infinitive: "verzinnen", past: "verzon", participle: "verzonnen", meaning_ru: "придумывать" },
  { infinitive: "verwerven", past: "verwierf", participle: "verworven", meaning_ru: "приобретать" },
  { infinitive: "verbinden", past: "verbond", participle: "verbonden", meaning_ru: "соединять" },
  { infinitive: "verstaan", past: "verstond", participle: "verstaan", meaning_ru: "понимать на слух" },
  { infinitive: "voorzien", past: "voorzag", participle: "voorzien", meaning_ru: "предусматривать" },
  { infinitive: "vergaan", past: "verging", participle: "vergaan", meaning_ru: "погибать" },
  { infinitive: "ontnemen", past: "ontnam", participle: "ontnomen", meaning_ru: "отнимать" },
];

export const SEED_NOUNS = [
  { word: "huis", article: "het", meaning_ru: "дом" },
  { word: "kind", article: "het", meaning_ru: "ребёнок" },
  { word: "meisje", article: "het", meaning_ru: "девочка" },
  { word: "boek", article: "het", meaning_ru: "книга" },
  { word: "water", article: "het", meaning_ru: "вода" },
  { word: "brood", article: "het", meaning_ru: "хлеб" },
  { word: "bier", article: "het", meaning_ru: "пиво" },
  { word: "eten", article: "het", meaning_ru: "еда" },
  { word: "jaar", article: "het", meaning_ru: "год" },
  { word: "station", article: "het", meaning_ru: "вокзал" },
  { word: "land", article: "het", meaning_ru: "страна" },
  { word: "geld", article: "het", meaning_ru: "деньги" },
  { word: "weer", article: "het", meaning_ru: "погода" },
  { word: "kantoor", article: "het", meaning_ru: "офис" },
  { word: "raam", article: "het", meaning_ru: "окно" },
  { word: "paard", article: "het", meaning_ru: "лошадь" },
  { word: "glas", article: "het", meaning_ru: "стакан" },
  { word: "bed", article: "het", meaning_ru: "кровать" },
  { word: "uur", article: "het", meaning_ru: "час" },
  { word: "feest", article: "het", meaning_ru: "праздник" },
  { word: "man", article: "de", meaning_ru: "мужчина" },
  { word: "vrouw", article: "de", meaning_ru: "женщина" },
  { word: "jongen", article: "de", meaning_ru: "мальчик" },
  { word: "moeder", article: "de", meaning_ru: "мама" },
  { word: "vader", article: "de", meaning_ru: "папа" },
  { word: "familie", article: "de", meaning_ru: "семья" },
  { word: "vriend", article: "de", meaning_ru: "друг" },
  { word: "tijd", article: "de", meaning_ru: "время" },
  { word: "week", article: "de", meaning_ru: "неделя" },
  { word: "dag", article: "de", meaning_ru: "день" },
  { word: "maand", article: "de", meaning_ru: "месяц" },
  { word: "avond", article: "de", meaning_ru: "вечер" },
  { word: "straat", article: "de", meaning_ru: "улица" },
  { word: "auto", article: "de", meaning_ru: "машина" },
  { word: "fiets", article: "de", meaning_ru: "велосипед" },
  { word: "stad", article: "de", meaning_ru: "город" },
  { word: "taal", article: "de", meaning_ru: "язык" },
  { word: "koffie", article: "de", meaning_ru: "кофе" },
  { word: "hond", article: "de", meaning_ru: "собака" },
  { word: "job", article: "de", meaning_ru: "работа" },
  { word: "probleem", article: "het", meaning_ru: "проблема" },
  { word: "idee", article: "het", meaning_ru: "идея" },
  { word: "antwoord", article: "het", meaning_ru: "ответ" },
  { word: "verhaal", article: "het", meaning_ru: "рассказ" },
  { word: "bos", article: "het", meaning_ru: "лес" },
  { word: "strand", article: "het", meaning_ru: "пляж" },
  { word: "meer", article: "het", meaning_ru: "озеро" },
  { word: "eiland", article: "het", meaning_ru: "остров" },
  { word: "hart", article: "het", meaning_ru: "сердце" },
  { word: "hoofd", article: "het", meaning_ru: "голова" },
  { word: "oog", article: "het", meaning_ru: "глаз" },
  { word: "oor", article: "het", meaning_ru: "ухо" },
  { word: "haar", article: "het", meaning_ru: "волосы" },
  { word: "lichaam", article: "het", meaning_ru: "тело" },
  { word: "gezicht", article: "het", meaning_ru: "лицо" },
  { word: "gevoel", article: "het", meaning_ru: "чувство" },
  { word: "leven", article: "het", meaning_ru: "жизнь" },
  { word: "ziekenhuis", article: "het", meaning_ru: "больница" },
  { word: "museum", article: "het", meaning_ru: "музей" },
  { word: "restaurant", article: "het", meaning_ru: "ресторан" },
  { word: "hotel", article: "het", meaning_ru: "отель" },
  { word: "zwembad", article: "het", meaning_ru: "бассейн" },
  { word: "vliegtuig", article: "het", meaning_ru: "самолёт" },
  { word: "ticket", article: "het", meaning_ru: "билет" },
  { word: "cadeau", article: "het", meaning_ru: "подарок" },
  { word: "ontbijt", article: "het", meaning_ru: "завтрак" },
  { word: "toilet", article: "het", meaning_ru: "туалет" },
  { word: "dak", article: "het", meaning_ru: "крыша" },
  { word: "ei", article: "het", meaning_ru: "яйцо" },
  { word: "stuk", article: "het", meaning_ru: "кусок" },
  { word: "naam", article: "de", meaning_ru: "имя" },
  { word: "school", article: "de", meaning_ru: "школа" },
  { word: "winkel", article: "de", meaning_ru: "магазин" },
  { word: "markt", article: "de", meaning_ru: "рынок" },
  { word: "kerk", article: "de", meaning_ru: "церковь" },
  { word: "brug", article: "de", meaning_ru: "мост" },
  { word: "zee", article: "de", meaning_ru: "море" },
  { word: "rivier", article: "de", meaning_ru: "река" },
  { word: "berg", article: "de", meaning_ru: "гора" },
  { word: "tafel", article: "de", meaning_ru: "стол" },
  { word: "stoel", article: "de", meaning_ru: "стул" },
  { word: "deur", article: "de", meaning_ru: "дверь" },
  { word: "tuin", article: "de", meaning_ru: "сад" },
  { word: "keuken", article: "de", meaning_ru: "кухня" },
  { word: "winter", article: "de", meaning_ru: "зима" },
  { word: "zomer", article: "de", meaning_ru: "лето" },
  { word: "lente", article: "de", meaning_ru: "весна" },
  { word: "herfst", article: "de", meaning_ru: "осень" },
  { word: "regen", article: "de", meaning_ru: "дождь" },
  { word: "zon", article: "de", meaning_ru: "солнце" },
  { word: "bloem", article: "de", meaning_ru: "цветок" },
  { word: "boom", article: "de", meaning_ru: "дерево" },
  { word: "muur", article: "de", meaning_ru: "стена" },
  { word: "vis", article: "de", meaning_ru: "рыба" },
  { word: "vogel", article: "de", meaning_ru: "птица" },
  { word: "soep", article: "de", meaning_ru: "суп" },
  { word: "wijn", article: "de", meaning_ru: "вино" },
  { word: "melk", article: "de", meaning_ru: "молоко" },
  { word: "thee", article: "de", meaning_ru: "чай" },
  { word: "collega", article: "de", meaning_ru: "коллега" },
  { word: "centrum", article: "het", meaning_ru: "центр" },
  { word: "prijs", article: "de", meaning_ru: "цена" },
  { word: "paspoort", article: "het", meaning_ru: "паспорт" },
  { word: "plek", article: "de", meaning_ru: "место" },
  { word: "verschil", article: "het", meaning_ru: "разница" },
  { word: "wereld", article: "de", meaning_ru: "мир" },
  { word: "bedrijf", article: "het", meaning_ru: "компания" },
  { word: "mens", article: "de", meaning_ru: "человек" },
  { word: "project", article: "het", meaning_ru: "проект" },
  { word: "persoon", article: "de", meaning_ru: "личность" },
  { word: "bericht", article: "het", meaning_ru: "сообщение" },
  { word: "buurman", article: "de", meaning_ru: "сосед" },
  { word: "cijfer", article: "het", meaning_ru: "оценка / цифра" },
  { word: "buurvrouw", article: "de", meaning_ru: "соседка" },
  { word: "getal", article: "het", meaning_ru: "число" },
  { word: "baby", article: "de", meaning_ru: "младенец" },
  { word: "examen", article: "het", meaning_ru: "экзамен" },
  { word: "tiener", article: "de", meaning_ru: "подросток" },
  { word: "diploma", article: "het", meaning_ru: "диплом" },
  { word: "student", article: "de", meaning_ru: "студент" },
  { word: "contract", article: "het", meaning_ru: "контракт" },
  { word: "leraar", article: "de", meaning_ru: "учитель" },
  { word: "apparaat", article: "het", meaning_ru: "устройство" },
  { word: "dokter", article: "de", meaning_ru: "врач" },
  { word: "scherm", article: "het", meaning_ru: "экран" },
  { word: "tandarts", article: "de", meaning_ru: "стоматолог" },
  { word: "toetsenbord", article: "het", meaning_ru: "клавиатура" },
  { word: "verpleegster", article: "de", meaning_ru: "медсестра" },
  { word: "wachtwoord", article: "het", meaning_ru: "пароль" },
  { word: "baas", article: "de", meaning_ru: "босс" },
  { word: "netwerk", article: "het", meaning_ru: "сеть" },
  { word: "werkgever", article: "de", meaning_ru: "работодатель" },
  { word: "programma", article: "het", meaning_ru: "программа" },
  { word: "werknemer", article: "de", meaning_ru: "работник" },
  { word: "document", article: "het", meaning_ru: "документ" },
  { word: "klant", article: "de", meaning_ru: "клиент" },
  { word: "formulier", article: "het", meaning_ru: "анкета" },
  { word: "gast", article: "de", meaning_ru: "гость" },
  { word: "pakket", article: "het", meaning_ru: "посылка" },
  { word: "buurt", article: "de", meaning_ru: "район" },
  { word: "adres", article: "het", meaning_ru: "адрес" },
  { word: "wijk", article: "de", meaning_ru: "квартал" },
  { word: "verzoek", article: "het", meaning_ru: "просьба" },
  { word: "provincie", article: "de", meaning_ru: "провинция" },
  { word: "advies", article: "het", meaning_ru: "совет" },
  { word: "hoofdstad", article: "de", meaning_ru: "столица" },
  { word: "besluit", article: "het", meaning_ru: "решение" },
  { word: "luchthaven", article: "de", meaning_ru: "аэропорт" },
  { word: "voorbeeld", article: "het", meaning_ru: "пример" },
  { word: "haven", article: "de", meaning_ru: "порт" },
  { word: "doel", article: "het", meaning_ru: "цель" },
  { word: "bus", article: "de", meaning_ru: "автобус" },
  { word: "plan", article: "het", meaning_ru: "план" },
  { word: "tram", article: "de", meaning_ru: "трамвай" },
  { word: "einde", article: "het", meaning_ru: "конец" },
  { word: "metro", article: "de", meaning_ru: "метро" },
  { word: "begin", article: "het", meaning_ru: "начало" },
  { word: "boot", article: "de", meaning_ru: "лодка" },
  { word: "midden", article: "het", meaning_ru: "середина" },
  { word: "taxi", article: "de", meaning_ru: "такси" },
  { word: "ijs", article: "het", meaning_ru: "мороженое / лёд" },
  { word: "straatlamp", article: "de", meaning_ru: "фонарь" },
  { word: "sap", article: "het", meaning_ru: "сок" },
  { word: "prullenbak", article: "de", meaning_ru: "мусорка" },
  { word: "vlees", article: "het", meaning_ru: "мясо" },
  { word: "bakker", article: "de", meaning_ru: "пекарь" },
  { word: "fruit", article: "het", meaning_ru: "фрукты" },
  { word: "slager", article: "de", meaning_ru: "мясник" },
  { word: "avondeten", article: "het", meaning_ru: "ужин" },
  { word: "apotheek", article: "de", meaning_ru: "аптека" },
  { word: "bord", article: "het", meaning_ru: "тарелка" },
  { word: "bibliotheek", article: "de", meaning_ru: "библиотека" },
  { word: "mes", article: "het", meaning_ru: "нож" },
  { word: "bioscoop", article: "de", meaning_ru: "кинотеатр" },
  { word: "kopje", article: "het", meaning_ru: "чашка" },
  { word: "bar", article: "de", meaning_ru: "бар" },
  { word: "servet", article: "het", meaning_ru: "салфетка" },
  { word: "discotheek", article: "de", meaning_ru: "дискотека" },
  { word: "tafelkleed", article: "het", meaning_ru: "скатерть" },
  { word: "afspraak", article: "de", meaning_ru: "встреча" },
  { word: "licht", article: "het", meaning_ru: "свет" },
  { word: "vergadering", article: "de", meaning_ru: "собрание" },
  { word: "vuur", article: "het", meaning_ru: "огонь" },
  { word: "pauze", article: "de", meaning_ru: "перерыв" },
  { word: "schip", article: "het", meaning_ru: "корабль" },
  { word: "vakantie", article: "de", meaning_ru: "отпуск" },
  { word: "meubilair", article: "het", meaning_ru: "мебель" },
  { word: "reis", article: "de", meaning_ru: "путешествие" },
  { word: "tapijt", article: "het", meaning_ru: "ковёр" },
  { word: "bagage", article: "de", meaning_ru: "багаж" },
  { word: "kussen", article: "het", meaning_ru: "подушка" },
  { word: "koffer", article: "de", meaning_ru: "чемодан" },
  { word: "laken", article: "het", meaning_ru: "простыня" },
  { word: "tas", article: "de", meaning_ru: "сумка" },
  { word: "bezoek", article: "het", meaning_ru: "визит" },
  { word: "portemonnee", article: "de", meaning_ru: "кошелёк" },
  { word: "gesprek", article: "het", meaning_ru: "разговор" },
  { word: "sleutel", article: "de", meaning_ru: "ключ" },
  { word: "succes", article: "het", meaning_ru: "успех" },
  { word: "bril", article: "de", meaning_ru: "очки" },
];

import { Verb } from "./models/Verb.js";
import { Noun } from "./models/Noun.js";
import { Stats } from "./models/Stats.js";

export async function seedIfNeeded() {
  const now = new Date();
  const verbRows = SEED_VERBS.map((v) => ({ ...v, next_review: now }));
  const nounRows = SEED_NOUNS.map((n) => ({ ...n, next_review: now }));

  const [verbsBefore, nounsBefore] = await Promise.all([Verb.count(), Noun.count()]);

  await Verb.bulkCreate(verbRows, { ignoreDuplicates: true });
  await Noun.bulkCreate(nounRows, { ignoreDuplicates: true });
  await Stats.findOrCreate({ where: { id: 1 }, defaults: { id: 1 } });

  const [verbsAfter, nounsAfter] = await Promise.all([Verb.count(), Noun.count()]);
  return {
    verbsAdded: verbsAfter - verbsBefore,
    nounsAdded: nounsAfter - nounsBefore,
    verbsTotal: verbsAfter,
    nounsTotal: nounsAfter,
  };
}
