export const SEED_VERBS = [
  { infinitive: "zijn", past: "was", participle: "geweest", meaning_ru: "быть" },
  { infinitive: "hebben", past: "had", participle: "gehad", meaning_ru: "иметь" },
  { infinitive: "gaan", past: "ging", participle: "gegaan", meaning_ru: "идти" },
  { infinitive: "komen", past: "kwam", participle: "gekomen", meaning_ru: "приходить" },
  { infinitive: "doen", past: "deed", participle: "gedaan", meaning_ru: "делать" },
  { infinitive: "zien", past: "zag", participle: "gezien", meaning_ru: "видеть" },
  { infinitive: "weten", past: "wist", participle: "geweten", meaning_ru: "знать" },
  { infinitive: "krijgen", past: "kreeg", participle: "gekregen", meaning_ru: "получать" },
  { infinitive: "geven", past: "gaf", participle: "gegeven", meaning_ru: "давать" },
  { infinitive: "nemen", past: "nam", participle: "genomen", meaning_ru: "брать" },
  { infinitive: "blijven", past: "bleef", participle: "gebleven", meaning_ru: "оставаться" },
  { infinitive: "lopen", past: "liep", participle: "gelopen", meaning_ru: "идти / бежать" },
  { infinitive: "staan", past: "stond", participle: "gestaan", meaning_ru: "стоять" },
  { infinitive: "zitten", past: "zat", participle: "gezeten", meaning_ru: "сидеть" },
  { infinitive: "liggen", past: "lag", participle: "gelegen", meaning_ru: "лежать" },
  { infinitive: "spreken", past: "sprak", participle: "gesproken", meaning_ru: "говорить" },
  { infinitive: "lezen", past: "las", participle: "gelezen", meaning_ru: "читать" },
  { infinitive: "schrijven", past: "schreef", participle: "geschreven", meaning_ru: "писать" },
  { infinitive: "drinken", past: "dronk", participle: "gedronken", meaning_ru: "пить" },
  { infinitive: "eten", past: "at", participle: "gegeten", meaning_ru: "есть (кушать)" },
  { infinitive: "slapen", past: "sliep", participle: "geslapen", meaning_ru: "спать" },
  { infinitive: "vinden", past: "vond", participle: "gevonden", meaning_ru: "находить" },
  { infinitive: "helpen", past: "hielp", participle: "geholpen", meaning_ru: "помогать" },
  { infinitive: "zwemmen", past: "zwom", participle: "gezwommen", meaning_ru: "плавать" },
  { infinitive: "vliegen", past: "vloog", participle: "gevlogen", meaning_ru: "летать" },
  { infinitive: "winnen", past: "won", participle: "gewonnen", meaning_ru: "выигрывать" },
  { infinitive: "begrijpen", past: "begreep", participle: "begrepen", meaning_ru: "понимать" },
  { infinitive: "rijden", past: "reed", participle: "gereden", meaning_ru: "ехать" },
  { infinitive: "vergeten", past: "vergat", participle: "vergeten", meaning_ru: "забывать" },
  { infinitive: "beginnen", past: "begon", participle: "begonnen", meaning_ru: "начинать" },
  { infinitive: "verliezen", past: "verloor", participle: "verloren", meaning_ru: "терять" },
  { infinitive: "sluiten", past: "sloot", participle: "gesloten", meaning_ru: "закрывать" },
  { infinitive: "breken", past: "brak", participle: "gebroken", meaning_ru: "ломать" },
  { infinitive: "trekken", past: "trok", participle: "getrokken", meaning_ru: "тянуть" },
  { infinitive: "roepen", past: "riep", participle: "geroepen", meaning_ru: "звать" },
  { infinitive: "bieden", past: "bood", participle: "geboden", meaning_ru: "предлагать" },
  { infinitive: "dragen", past: "droeg", participle: "gedragen", meaning_ru: "носить" },
  { infinitive: "zingen", past: "zong", participle: "gezongen", meaning_ru: "петь" },
  { infinitive: "springen", past: "sprong", participle: "gesprongen", meaning_ru: "прыгать" },
  { infinitive: "vechten", past: "vocht", participle: "gevochten", meaning_ru: "драться" },
  { infinitive: "werpen", past: "wierp", participle: "geworpen", meaning_ru: "бросать" },
  { infinitive: "sterven", past: "stierf", participle: "gestorven", meaning_ru: "умирать" },
  { infinitive: "kiezen", past: "koos", participle: "gekozen", meaning_ru: "выбирать" },
  { infinitive: "bewegen", past: "bewoog", participle: "bewogen", meaning_ru: "двигать(ся)" },
  { infinitive: "verlaten", past: "verliet", participle: "verlaten", meaning_ru: "покидать" },
  { infinitive: "vergelijken", past: "vergeleek", participle: "vergeleken", meaning_ru: "сравнивать" },
  { infinitive: "genieten", past: "genoot", participle: "genoten", meaning_ru: "наслаждаться" },
  { infinitive: "verdwijnen", past: "verdween", participle: "verdwenen", meaning_ru: "исчезать" },
  { infinitive: "snijden", past: "sneed", participle: "gesneden", meaning_ru: "резать" },
  { infinitive: "binden", past: "bond", participle: "gebonden", meaning_ru: "связывать" },
  { infinitive: "kruipen", past: "kroop", participle: "gekropen", meaning_ru: "ползти" },
  { infinitive: "zwijgen", past: "zweeg", participle: "gezwegen", meaning_ru: "молчать" },
  { infinitive: "wegen", past: "woog", participle: "gewogen", meaning_ru: "взвешивать" },
  { infinitive: "wijzen", past: "wees", participle: "gewezen", meaning_ru: "указывать" },
  { infinitive: "graven", past: "groef", participle: "gegraven", meaning_ru: "копать" },
  { infinitive: "hangen", past: "hing", participle: "gehangen", meaning_ru: "висеть" },
  { infinitive: "blazen", past: "blies", participle: "geblazen", meaning_ru: "дуть" },
  { infinitive: "stelen", past: "stal", participle: "gestolen", meaning_ru: "красть" },
  { infinitive: "vriezen", past: "vroor", participle: "gevroren", meaning_ru: "морозить" },
  { infinitive: "lijken", past: "leek", participle: "geleken", meaning_ru: "казаться" },
];

export const SEED_NOUNS = [
  { word: "huis", article: "het", meaning_ru: "дом" },
  { word: "kind", article: "het", meaning_ru: "ребёнок" },
  { word: "meisje", article: "het", meaning_ru: "девочка" },
  { word: "boek", article: "het", meaning_ru: "книга" },
  { word: "water", article: "het", meaning_ru: "вода" },
  { word: "brood", article: "het", meaning_ru: "хлеб" },
  { word: "bier", article: "het", meaning_ru: "пиво" },
  { word: "eten", article: "het", meaning_ru: "еда" },
  { word: "jaar", article: "het", meaning_ru: "год" },
  { word: "station", article: "het", meaning_ru: "вокзал" },
  { word: "land", article: "het", meaning_ru: "страна" },
  { word: "geld", article: "het", meaning_ru: "деньги" },
  { word: "weer", article: "het", meaning_ru: "погода" },
  { word: "kantoor", article: "het", meaning_ru: "офис" },
  { word: "raam", article: "het", meaning_ru: "окно" },
  { word: "paard", article: "het", meaning_ru: "лошадь" },
  { word: "glas", article: "het", meaning_ru: "стакан" },
  { word: "bed", article: "het", meaning_ru: "кровать" },
  { word: "uur", article: "het", meaning_ru: "час" },
  { word: "feest", article: "het", meaning_ru: "праздник" },
  { word: "man", article: "de", meaning_ru: "мужчина" },
  { word: "vrouw", article: "de", meaning_ru: "женщина" },
  { word: "jongen", article: "de", meaning_ru: "мальчик" },
  { word: "moeder", article: "de", meaning_ru: "мама" },
  { word: "vader", article: "de", meaning_ru: "папа" },
  { word: "familie", article: "de", meaning_ru: "семья" },
  { word: "vriend", article: "de", meaning_ru: "друг" },
  { word: "tijd", article: "de", meaning_ru: "время" },
  { word: "week", article: "de", meaning_ru: "неделя" },
  { word: "dag", article: "de", meaning_ru: "день" },
  { word: "maand", article: "de", meaning_ru: "месяц" },
  { word: "avond", article: "de", meaning_ru: "вечер" },
  { word: "straat", article: "de", meaning_ru: "улица" },
  { word: "auto", article: "de", meaning_ru: "машина" },
  { word: "fiets", article: "de", meaning_ru: "велосипед" },
  { word: "stad", article: "de", meaning_ru: "город" },
  { word: "taal", article: "de", meaning_ru: "язык" },
  { word: "koffie", article: "de", meaning_ru: "кофе" },
  { word: "hond", article: "de", meaning_ru: "собака" },
  { word: "job", article: "de", meaning_ru: "работа" },
  { word: "probleem", article: "het", meaning_ru: "проблема" },
  { word: "idee", article: "het", meaning_ru: "идея" },
  { word: "antwoord", article: "het", meaning_ru: "ответ" },
  { word: "verhaal", article: "het", meaning_ru: "рассказ" },
  { word: "bos", article: "het", meaning_ru: "лес" },
  { word: "strand", article: "het", meaning_ru: "пляж" },
  { word: "meer", article: "het", meaning_ru: "озеро" },
  { word: "eiland", article: "het", meaning_ru: "остров" },
  { word: "hart", article: "het", meaning_ru: "сердце" },
  { word: "hoofd", article: "het", meaning_ru: "голова" },
  { word: "oog", article: "het", meaning_ru: "глаз" },
  { word: "oor", article: "het", meaning_ru: "ухо" },
  { word: "haar", article: "het", meaning_ru: "волосы" },
  { word: "lichaam", article: "het", meaning_ru: "тело" },
  { word: "gezicht", article: "het", meaning_ru: "лицо" },
  { word: "gevoel", article: "het", meaning_ru: "чувство" },
  { word: "leven", article: "het", meaning_ru: "жизнь" },
  { word: "ziekenhuis", article: "het", meaning_ru: "больница" },
  { word: "museum", article: "het", meaning_ru: "музей" },
  { word: "restaurant", article: "het", meaning_ru: "ресторан" },
  { word: "hotel", article: "het", meaning_ru: "отель" },
  { word: "zwembad", article: "het", meaning_ru: "бассейн" },
  { word: "vliegtuig", article: "het", meaning_ru: "самолёт" },
  { word: "ticket", article: "het", meaning_ru: "билет" },
  { word: "cadeau", article: "het", meaning_ru: "подарок" },
  { word: "ontbijt", article: "het", meaning_ru: "завтрак" },
  { word: "toilet", article: "het", meaning_ru: "туалет" },
  { word: "dak", article: "het", meaning_ru: "крыша" },
  { word: "ei", article: "het", meaning_ru: "яйцо" },
  { word: "stuk", article: "het", meaning_ru: "кусок" },
  { word: "naam", article: "de", meaning_ru: "имя" },
  { word: "school", article: "de", meaning_ru: "школа" },
  { word: "winkel", article: "de", meaning_ru: "магазин" },
  { word: "markt", article: "de", meaning_ru: "рынок" },
  { word: "kerk", article: "de", meaning_ru: "церковь" },
  { word: "brug", article: "de", meaning_ru: "мост" },
  { word: "zee", article: "de", meaning_ru: "море" },
  { word: "rivier", article: "de", meaning_ru: "река" },
  { word: "berg", article: "de", meaning_ru: "гора" },
  { word: "tafel", article: "de", meaning_ru: "стол" },
  { word: "stoel", article: "de", meaning_ru: "стул" },
  { word: "deur", article: "de", meaning_ru: "дверь" },
  { word: "tuin", article: "de", meaning_ru: "сад" },
  { word: "keuken", article: "de", meaning_ru: "кухня" },
  { word: "winter", article: "de", meaning_ru: "зима" },
  { word: "zomer", article: "de", meaning_ru: "лето" },
  { word: "lente", article: "de", meaning_ru: "весна" },
  { word: "herfst", article: "de", meaning_ru: "осень" },
  { word: "regen", article: "de", meaning_ru: "дождь" },
  { word: "zon", article: "de", meaning_ru: "солнце" },
  { word: "bloem", article: "de", meaning_ru: "цветок" },
  { word: "boom", article: "de", meaning_ru: "дерево" },
  { word: "muur", article: "de", meaning_ru: "стена" },
  { word: "vis", article: "de", meaning_ru: "рыба" },
  { word: "vogel", article: "de", meaning_ru: "птица" },
  { word: "soep", article: "de", meaning_ru: "суп" },
  { word: "wijn", article: "de", meaning_ru: "вино" },
  { word: "melk", article: "de", meaning_ru: "молоко" },
  { word: "thee", article: "de", meaning_ru: "чай" },
  { word: "collega", article: "de", meaning_ru: "коллега" },
];

import { Verb } from "./models/Verb.js";
import { Noun } from "./models/Noun.js";
import { Stats } from "./models/Stats.js";

export async function seedIfNeeded() {
  const now = new Date();
  const verbRows = SEED_VERBS.map((v) => ({ ...v, next_review: now }));
  const nounRows = SEED_NOUNS.map((n) => ({ ...n, next_review: now }));

  const [verbsBefore, nounsBefore] = await Promise.all([Verb.count(), Noun.count()]);

  await Verb.bulkCreate(verbRows, { ignoreDuplicates: true });
  await Noun.bulkCreate(nounRows, { ignoreDuplicates: true });
  await Stats.findOrCreate({ where: { id: 1 }, defaults: { id: 1 } });

  const [verbsAfter, nounsAfter] = await Promise.all([Verb.count(), Noun.count()]);
  return {
    verbsAdded: verbsAfter - verbsBefore,
    nounsAdded: nounsAfter - nounsBefore,
    verbsTotal: verbsAfter,
    nounsTotal: nounsAfter,
  };
}
